spring:
  datasource:
    url: jdbc:h2:mem:cryptoRecsDb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    showSql: true
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  h2.console.enabled: true